#
#  This FW update SHA and create a new PR in homebrew-TwoPi
#
name: Release

on:
  release:
    types:
      - created
  
jobs:
  update_formula_version:
    name: Bump Homebrew formula
    #runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: bump-formula-pr
#        if: "!contains(github.ref, '-')" # skip prereleases (uncomment this later)
        env: 
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREWRELEASETOKEN }}
        run: |	
          echo ${{github.event.release.tag_name}}
          SRC_URL="https://github.com/piScope/Test/archive/refs/tags/"${{ github.event.release.tag_name }}".tar.gz"
          echo "${SRC_URL}"
          #
          # (this is for MacOS runner)
          # printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
          #
          TAG_VERSION=$(echo ${{github.event.release.tag_name}} | sed 's/[^0-9.]*//g')
          echo "TAG_VERSION=$(echo ${{github.event.release.tag_name}} | sed 's/[^0-9.]*//g')" >> $GITHUB_ENV
          #
          export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.BREWRELEASETOKEN }}
          brew tap piScope/twopi
          cd $(brew --repo piScope/twopi)
          echo "SRC_REPO=$(brew --repo piScope/twopi)" >> $GITHUB_ENV	  	  
          pwd
          ls -l
          #git remote -v
          git config --global user.name 'sshiraiwa'
          git config --global user.email 'shiraiwa@princeton.edu'
          #git config --global credential.helper cache
          #A=https://x-access-token:
          #B=${{ secrets.BREWRELEASETOKEN }}
          #C=@github.com/piscope/homebrew-TwoPi
          #ABC="${A}""${B}""${C}"
          #echo ${A}
          #echo ${ABC}
          #git remote set-url origin ${ABC}
          git remote -v
          echo ${{ github.actor }}
          brew bump-formula-pr -f -d -v --no-fork --write --no-browse --no-audit --url "${SRC_URL}" piscope/twopi/test
          git checkout --no-track -b bump-test-${TAG_VERSION} origin/master
          git add ./test.rb	  
          git commit --no-edit --verbose --message='test '${TAG_VERSION} -- ./test.rb
          cat test.rb

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ${{ env.SRC_REPO }}
          destination-repository-name: 'bump-test-0.1.0'
          destination-github-username: 'piScope'	  
          user-email: shiraiwa@princeton.edu
          target-branch: master




