#
#  This FW update SHA and create a new PR in homebrew-TwoPi
#
name: Release

on:
  release:
    types:
      - created
  
jobs:
  update_formula_version:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: bump-formula-pr
#        if: "!contains(github.ref, '-')" # skip prereleases (uncomment this later)
        env: 
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREWRELEASETOKEN }}
        run: |	
          echo ${{github.event.release.tag_name}}
          SRC_URL="https://github.com/piScope/Test/archive/refs/tags/"${{ github.event.release.tag_name }}".tar.gz"
          echo "${SRC_URL}"
          printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
          export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.BREWRELEASETOKEN }}
          brew tap piScope/twopi
          cd $(brew --repo piScope/twopi)
          git remote -v
          git config --global user.name 'sshiraiwa'
          git config --global user.email 'shiraiwa@princeton.edu'
          git config --global credential.helper cache
          A=https://x-access-token:${{ secrets.BREWRELEASETOKEN }}
          B=${A}@github.com/piscope/homebrew-TwoPi
          echo $B
          git remote set-url origin $B
          git remote -v
          echo ${{ github.actor }}
          brew bump-formula-pr -f -d -v --no-fork --no-browse --no-audit --url "${SRC_URL}" piscope/twopi/test



